// Exportación de todos los controladores
export * from "./auth-controller/auth.controller"
export * from "./mipres-controller/prescripcion-controller/prescripcion.controller"
export * from "./mipres-controller/direccionamiento-controller/direccionamiento.controller"
export * from "./mipres-controller/no-direccionamiento-controller/no-direccionamiento.controller"
export * from "./mipres-controller/tutela-controller/tutela.controller"
export * from "./mipres-controller/reporte-entrega-controller/reporte-entrega.controller"
export * from "./mipres-controller/suministro-controller/suministro.controller"
export * from "./mipres-controller/programacion-controller/programacion.controller"
export * from "./mipres-controller/entrega-controller/entrega.controller"
export * from "./usuarios-controller/usuarios.controller"
export * from "./reportes-controller/reportes.controller"
export * from "./permisos-controller/permisos.controller"
